### 1) Load Dataset

In [1]:
import pandas as pd
df_hr = pd.read_csv('hr_dataset.csv')

In [2]:
df_hr.head()         # df_hr.sample(5)

,Unnamed: 0,Employee_ID,Full_Name,Department,Job_Title,Hire_Date,Location,Performance_Rating,Experience_Years,Status,Work_Mode,Salary_INR
0,0,EMP0000001,Joshua Nguyen,IT,Software Engineer,2011-08-10,"Isaacland, Denmark",5,14,Resigned,On-site,1585363
1,1,EMP0000002,Julie Williams,Marketing,SEO Specialist,2018-03-02,"Anthonyside, Costa Rica",2,7,Active,On-site,847686
2,2,EMP0000003,Alyssa Martinez,HR,HR Manager,2023-03-20,"Port Christinaport, Saudi Arabia",1,2,Active,On-site,1430084
3,3,EMP0000004,Nicholas Valdez,IT,Software Engineer,2023-10-12,"Port Shelbychester, Antigua and Barbuda",1,1,Active,On-site,990689
4,4,EMP0000005,Joel Hendricks,Operations,Logistics Coordinator,2024-12-09,"Lake Kimberly, Palestinian Territory",5,0,Active,On-site,535082

### 2) Column Cleaning and Standardization

In [3]:
df_hr.columns

Index(['Unnamed: 0', 'Employee_ID', 'Full_Name', 'Department', 'Job_Title',
       'Hire_Date', 'Location', 'Performance_Rating', 'Experience_Years',
       'Status', 'Work_Mode', 'Salary_INR'],
      dtype='str')

In [4]:
df_hr = df_hr.drop(columns = ['Unnamed: 0'])

In [5]:
# We convert columns to snake_case to make names consistent, easy to read, and SQL/Python friendly. It avoids spaces/special characters
# and prevent errors when writing queries or code.
df_hr.columns = df_hr.columns.str.lower()
df_hr.columns

Index(['employee_id', 'full_name', 'department', 'job_title', 'hire_date',
       'location', 'performance_rating', 'experience_years', 'status',
       'work_mode', 'salary_inr'],
      dtype='str')

In [6]:
df_hr.rename(columns = {'full_name':'name', 'salary_inr':'salary'}, inplace = True)

### 3) Data Type Inspection

In [7]:
df_hr.info() # To know the basic information of the dataset like the datatype of each column and the total no.of records

<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   employee_id         str
 1   name                str
 2   department          str
 3   job_title           str
 4   hire_date           str
 5   location            str
 6   performance_rating  int64
 7   experience_years    int64
 8   status              str
 9   work_mode           str
 10  salary              int64
dtypes: int64(3), str(8)
memory usage: 167.8 MB

### 4) Missing Value Check

In [8]:
df_hr.isnull().sum() # To check for no.of null values over each column

employee_id           0
name                  0
department            0
job_title             0
hire_date             0
location              0
performance_rating    0
experience_years      0
status                0
work_mode             0
salary                0
dtype: int64

### 5) Descriptive Statistical Summary

In [9]:
df_hr.describe(include = 'all') # Summary stats of both numeric and categorical columns

,employee_id,name,department,job_title,hire_date,location,performance_rating,experience_years,status,work_mode,salary
count,2000000,2000000,2000000,2000000,2000000,2000000,2.000000e+06,2.000000e+06,2000000,2000000,2.000000e+06
unique,2000000,467487,7,29,5479,1593497,NaN,NaN,4,2,NaN
top,EMP0000001,Michael Smith,IT,Software Engineer,2022-10-31,"Lake Michael, Congo",NaN,NaN,Active,On-site,NaN
freq,1,1014,601042,300358,622,20,NaN,NaN,1401558,1199109,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,3.000148e+00,5.010287e+00,NaN,NaN,8.968878e+05
std,NaN,NaN,NaN,NaN,NaN,NaN,1.413973e+00,3.608823e+00,NaN,NaN,4.026103e+05
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,0.000000e+00,NaN,NaN,3.000000e+05
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,2.000000e+00,NaN,NaN,6.163460e+05
50%,NaN,NaN,NaN,NaN,NaN,NaN,3.000000e+00,5.000000e+00,NaN,NaN,8.110265e+05
75%,NaN,NaN,NaN,NaN,NaN,NaN,4.000000e+00,8.000000e+00,NaN,NaN,1.073745e+06
max,NaN,NaN,NaN,NaN,NaN,NaN,5.000000e+00,1.500000e+01,NaN,NaN,2.999976e+06

### 6) Data Validation, Exploration, and Cleaning

In [10]:
df_hr.duplicated().sum()

np.int64(0)

In [11]:
# Quality Check: This below line of code should return empty table with column headers.
df_hr.loc[(df_hr['employee_id'].str[0:3] != 'EMP') | (df_hr['employee_id'].str.len() != 10)]  

df_hr['employee_id'] = df_hr['employee_id'].str.replace('EMP','')
df_hr['employee_id'] = df_hr['employee_id'].str.lstrip('0')
df_hr['employee_id'] = df_hr['employee_id'].astype(int)
print(f'duplicate records: {df_hr['employee_id'].duplicated().sum()}')
df_hr['employee_id']

duplicate records: 0

0                1
1                2
2                3
3                4
4                5
            ...
1999995    1999996
1999996    1999997
1999997    1999998
1999998    1999999
1999999    2000000
Name: employee_id, Length: 2000000, dtype: int64

In [12]:
df_hr

,employee_id,name,department,job_title,hire_date,location,performance_rating,experience_years,status,work_mode,salary
0,1,Joshua Nguyen,IT,Software Engineer,2011-08-10,"Isaacland, Denmark",5,14,Resigned,On-site,1585363
1,2,Julie Williams,Marketing,SEO Specialist,2018-03-02,"Anthonyside, Costa Rica",2,7,Active,On-site,847686
2,3,Alyssa Martinez,HR,HR Manager,2023-03-20,"Port Christinaport, Saudi Arabia",1,2,Active,On-site,1430084
3,4,Nicholas Valdez,IT,Software Engineer,2023-10-12,"Port Shelbychester, Antigua and Barbuda",1,1,Active,On-site,990689
4,5,Joel Hendricks,Operations,Logistics Coordinator,2024-12-09,"Lake Kimberly, Palestinian Territory",5,0,Active,On-site,535082
...,...,...,...,...,...,...,...,...,...,...,...
1999995,1999996,Cody Russell,Operations,Logistics Coordinator,2010-08-31,"Casefurt, Serbia",3,14,Active,Remote,657648
1999996,1999997,Tracey Smith,IT,Software Engineer,2021-05-07,"Dannyport, Kuwait",3,4,Active,On-site,1030109
1999997,1999998,Tracy Lee,Sales,Business Development Manager,2024-05-29,"Craighaven, Nigeria",5,1,Active,Remote,1313085
1999998,1999999,Michael Roberson,IT,Software Engineer,2023-02-14,"Jonathanmouth, Djibouti",4,2,Retired,On-site,1479727
1999999,2000000,Angela Lambert,HR,Talent Acquisition Specialist,2020-11-11,"Morganchester, Canada",1,4,Active,Remote,993718

In [13]:
# Check number of distinct employee names
df_hr['name'].nunique()

467487

In [14]:
# Check distinct departments
df_hr['department'].unique()

<StringArray>
['IT', 'Marketing', 'HR', 'Operations', 'Finance', 'Sales', 'R&D']
Length: 7, dtype: str

In [15]:
# Check distinct job titles
df_hr['job_title'].unique()

<StringArray>
[            'Software Engineer',                'SEO Specialist',
                    'HR Manager',         'Logistics Coordinator',
               'Finance Manager',               'Account Manager',
             'Financial Analyst',               'Sales Executive',
          'Operations Executive',                  'HR Executive',
                'Sales Director',               'DevOps Engineer',
            'Content Strategist',           'Marketing Executive',
            'Research Scientist',                    'Accountant',
                    'IT Manager',          'Supply Chain Manager',
                  'Data Analyst', 'Talent Acquisition Specialist',
             'Product Developer',           'Operations Director',
                           'CTO',  'Business Development Manager',
                'Lab Technician',                           'CFO',
                 'Brand Manager',                   'HR Director',
            'Innovation Manager']
Length: 29, dtype: str

In [16]:
# Check job titles by department

pd.set_option('display.max_colwidth', None) # this line of code ensures proper visibility of the output
df_hr.groupby('department')['job_title'].unique()

department
Finance                                          [Finance Manager, Financial Analyst, Accountant, CFO]
HR                              [HR Manager, HR Executive, Talent Acquisition Specialist, HR Director]
IT                                 [Software Engineer, DevOps Engineer, IT Manager, Data Analyst, CTO]
Marketing                     [SEO Specialist, Content Strategist, Marketing Executive, Brand Manager]
Operations    [Logistics Coordinator, Operations Executive, Supply Chain Manager, Operations Director]
R&D                        [Research Scientist, Product Developer, Lab Technician, Innovation Manager]
Sales                 [Account Manager, Sales Executive, Sales Director, Business Development Manager]
Name: job_title, dtype: object

In [17]:
# Change the datatype of hire_date from str to date
df_hr['hire_date'] = pd.to_datetime(df_hr['hire_date'])
df_hr.dtypes

employee_id                    int64
name                             str
department                       str
job_title                        str
hire_date             datetime64[us]
location                         str
performance_rating             int64
experience_years               int64
status                           str
work_mode                        str
salary                         int64
dtype: object

In [18]:
# Check hire date column range
print(f'First hire date: {df_hr['hire_date'].min()}')
print(f'Last hire date: {df_hr['hire_date'].max()}')

First hire date: 2010-08-14 00:00:00
Last hire date: 2025-08-13 00:00:00

In [19]:
# Split location into city and country

df_hr[['city','country']] = df_hr['location'].str.split(',', n = 1, expand = True)
# expand=True makes the split results into separate columns in a DataFrame instead of returning them as a list.

df_hr.drop(columns = 'location', inplace = True)

# To prevent hidden space errors in grouping
df_hr['city'] = df_hr['city'].str.strip()
df_hr['country'] = df_hr['country'].str.strip()

In [20]:
df_hr.isnull().sum()

employee_id           0
name                  0
department            0
job_title             0
hire_date             0
performance_rating    0
experience_years      0
status                0
work_mode             0
salary                0
city                  0
country               0
dtype: int64

In [21]:
df_hr

,employee_id,name,department,job_title,hire_date,performance_rating,experience_years,status,work_mode,salary,city,country
0,1,Joshua Nguyen,IT,Software Engineer,2011-08-10,5,14,Resigned,On-site,1585363,Isaacland,Denmark
1,2,Julie Williams,Marketing,SEO Specialist,2018-03-02,2,7,Active,On-site,847686,Anthonyside,Costa Rica
2,3,Alyssa Martinez,HR,HR Manager,2023-03-20,1,2,Active,On-site,1430084,Port Christinaport,Saudi Arabia
3,4,Nicholas Valdez,IT,Software Engineer,2023-10-12,1,1,Active,On-site,990689,Port Shelbychester,Antigua and Barbuda
4,5,Joel Hendricks,Operations,Logistics Coordinator,2024-12-09,5,0,Active,On-site,535082,Lake Kimberly,Palestinian Territory
...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,1999996,Cody Russell,Operations,Logistics Coordinator,2010-08-31,3,14,Active,Remote,657648,Casefurt,Serbia
1999996,1999997,Tracey Smith,IT,Software Engineer,2021-05-07,3,4,Active,On-site,1030109,Dannyport,Kuwait
1999997,1999998,Tracy Lee,Sales,Business Development Manager,2024-05-29,5,1,Active,Remote,1313085,Craighaven,Nigeria
1999998,1999999,Michael Roberson,IT,Software Engineer,2023-02-14,4,2,Retired,On-site,1479727,Jonathanmouth,Djibouti
1999999,2000000,Angela Lambert,HR,Talent Acquisition Specialist,2020-11-11,1,4,Active,Remote,993718,Morganchester,Canada

In [22]:
# Check distinct values of performance_rating
df_hr['performance_rating'].unique()

array([5, 2, 1, 4, 3])

In [23]:
# Check the experience range of employees
print(df_hr['experience_years'].agg(['min','max']))
df_hr['experience_years'].unique()

min     0
max    15
Name: experience_years, dtype: int64

array([14,  7,  2,  1,  0,  4,  9,  5,  6,  8,  3, 10, 11, 12, 13, 15])

In [24]:
# Check distinct values of status
df_hr['status'].unique()

<StringArray>
['Resigned', 'Active', 'Terminated', 'Retired']
Length: 4, dtype: str

In [25]:
# Check distinct values of work_mode
df_hr['work_mode'].unique()

<StringArray>
['On-site', 'Remote']
Length: 2, dtype: str

In [26]:
# Check the salary range 
print(f'Minimum salary : {df_hr['salary'].min()}')
print(f'Maximum salary : {df_hr['salary'].max()}')

print(f'Minimum salary of an active employee: {df_hr.loc[df_hr['status'] == 'Active']['salary'].min()}')
print(f'Maximum salary of an active employee: {df_hr.loc[df_hr['status'] == 'Active']['salary'].max()}')

Minimum salary : 300000
Maximum salary : 2999976
Minimum salary of an active employee: 300018
Maximum salary of an active employee: 2999976

In [27]:
# Check the number of distinct cities
df_hr['city'].nunique()

104479

In [28]:
# Check the number of distinct countries
df_hr['country'].nunique()

243

### 7) Feature Engineering and Segmentation

In [29]:
# Business-driven experience segmentation for workforce analysis
df_hr['experience_level'] = pd.cut(df_hr['experience_years'], bins =[0, 2, 5, 10, 20], labels = ['Junior','Mid','Senior','Expert'],
                                   include_lowest = True) # [0,2], (2,5], (5,10], (10,20]

# Salary Bands
df_hr['salary_band'] = pd.qcut(df_hr['salary'], q = 4, labels = ['Low', 'Medium', 'High', 'Very High'])

# Employee Status Category
df_hr['attrition'] = df_hr['status'].apply(lambda x : 0 if x == 'Active' else 1) # Helps calculate attrition rate easily

In [30]:
df_hr.sample(5)

,employee_id,name,department,job_title,hire_date,performance_rating,experience_years,status,work_mode,salary,city,country,experience_level,salary_band,attrition
1090431,1090432,Stephanie Benton,IT,Software Engineer,2020-05-22,1,5,Active,On-site,602517,Warrenfort,Gibraltar,Mid,Low,0
1566670,1566671,Tina Peterson,Marketing,Marketing Executive,2016-08-29,2,8,Active,On-site,916777,Lake Danashire,Belize,Senior,High,0
1218049,1218050,Juan Tanner,IT,Data Analyst,2023-03-30,2,2,Retired,On-site,1149241,Rhondahaven,Korea,Junior,Very High,1
290148,290149,Ms. Kathleen Reyes,IT,DevOps Engineer,2021-07-14,5,4,Resigned,Remote,816639,Rachelberg,Cayman Islands,Mid,High,1
1302814,1302815,David Garcia,HR,Talent Acquisition Specialist,2023-11-01,3,1,Active,Remote,953998,Jacksonberg,Turkmenistan,Junior,High,0

In [31]:
# Quality Check
print(df_hr['experience_level'].unique())
print(df_hr['salary_band'].unique())
print(df_hr['attrition'].unique())

['Expert', 'Senior', 'Junior', 'Mid']
Categories (4, str): ['Junior' < 'Mid' < 'Senior' < 'Expert']
['Very High', 'High', 'Low', 'Medium']
Categories (4, str): ['Low' < 'Medium' < 'High' < 'Very High']
[1 0]

### 8) Data Loading to SQL Server

In [36]:
# Load the data into sql server
from sqlalchemy import create_engine, text

server = 'Kiran\\SQLEXPRESS'
database = 'hr_analytics'

engine = create_engine(f"mssql+pyodbc://@{server}/{database}"
                      "?driver=ODBC+Driver+17+for+SQL+Server"
                      "&trusted_connection=yes"
                      )

with engine.begin() as conn:
    conn.execute(text('''IF OBJECT_ID('dbo.employee_analytics', 'U') IS NOT NULL
                            TRUNCATE TABLE dbo.employee_analytics;''')) # it keeps the table structure and deletes the data

df_hr.to_sql("employee_analytics", con = engine, index = False, chunksize = 50000, if_exists = 'append') # now we append the data to the empty table

<>:4: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:4: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\kalis\AppData\Local\Temp\ipykernel_17448\3035409787.py:4: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  server = 'Kiran\SQLEXPRESS'
C:\Users\kalis\AppData\Local\Programs\Python\Python314\Lib\contextlib.py:141: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  return next(self.gen)

3960